add loongarch64 support in configure.ac and configure
loongarch64/cpython pull request #1
Opened 2022-01-24 03:42 UTC by loongson-zn

``` 
# install the Makefile of the shared python build
sed -e 's,gcc-8,gcc,;s,g++-8,g++,'  -e '/^OPT/s,-O3,-O2,' -e 's/-O3/-O2/g' -e 's/-fprofile-use *-fprofile-correction//g' -e 's/-fstack-protector /-fstack-protector-strong /g' -e 's/-specs=[^ ]*//g' -e 's/-fdebug-prefix-map=[^ ]*//g' -e 's,^RUNSHARED *=.*,RUNSHARED=,' -e '/BLDLIBRARY/s/-L\. //' \
	/home/loongson/zhangna/python3.9/python3.9-3.9.2/build-shared/Makefile \
	> debian/tmp/usr/lib/python3.9/config-3.9-loongarch64-linux-gnu/Makefile
/bin/bash: debian/tmp/usr/lib/python3.9/config-3.9-loongarch64-linux-gnu/Makefile: No such file or directory
make: *** [debian/rules:865：stamps/stamp-install] 错误 1
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
```

最近在debian上编译python3.9  有个报错，发现configure/configure.ac 中没有loongarch64 platform triplet， 因此加了这个patch。请review @loongarch64/dev-team 
其次，在我刚才创建PR的时候，是要求在https://bugs.python.org/ 先有一个issue

2022-01-24 05:04 UTC, loongson-zn commented
https://bugs.python.org/issue46498

2022-01-25 03:54 UTC, huolinjue commented
我觉得configure不应该手动修改，该文件由configure.ac经由autoconf（或autoreconf）生成。

2022-01-25 04:55 UTC, loongson-zn commented
好提议

2022-01-25 11:10 UTC, zhuyaliang commented
我认为既然上游包含configure 这个文件，那么这个文件也需要修改.再来看看 README.rst
```
    ./configure
    make
    make test
    sudo make install
```
也是直接运行configure，所以我同意这个PR

2022-01-25 11:10 UTC, zhuyaliang approved these changes
good

2022-01-25 11:23 UTC, sulit approved these changes
看着没什么问题

2022-01-25 11:28 UTC, fangyaling approved these changes
Approve

2022-01-25 11:28 UTC, xen0n requested changes

2022-01-25 11:28 UTC, xen0n commented on configure
> +        loongarch64-linux-gnu
这处是手工改出来的吗？我印象中 autotools 生成 configure 都会带上大量行号，没道理一个都没变。

请确认一下，确认好之前我先 block merge 了 ;-)

2022-01-25 12:49 UTC, loongson-zn commented on configure
> +        loongarch64-linux-gnu
```diff
diff -Naur cpython.orj/configure cpython/configure
 --- cpython.orj/configure   2022-01-25 20:30:55.729798466 +0800
 +++ cpython/configure   2022-01-25 20:32:47.137824831 +0800
 @@ -5993,6 +5993,8 @@
          hppa-linux-gnu
  # elif defined(__ia64__)
          ia64-linux-gnu
 +# elif defined(__loongarch64)
 +        loongarch64-linux-gnu
  # elif defined(__m68k__) && !defined(__mcoldfire__)
          m68k-linux-gnu
  # elif defined(__mips_hard_float) && defined(__mips_isa_rev) && (__mips_isa_rev >=6) &&              defined(_MIPSEL)
 diff -Naur cpython.orj/configure.ac cpython/configure.ac
 --- cpython.orj/configure.ac    2022-01-25 20:30:55.733798324 +0800
 +++ cpython/configure.ac    2022-01-25 20:32:40.146074156 +0800
 @@ -884,6 +884,8 @@
          hppa-linux-gnu
  # elif defined(__ia64__)
          ia64-linux-gnu
 +# elif defined(__loongarch64)
 +        loongarch64-linux-gnu
  # elif defined(__m68k__) && !defined(__mcoldfire__)
          m68k-linux-gnu
  # elif defined(__mips_hard_float) && defined(__mips_isa_rev) && (__mips_isa_rev >=6) &&              defined(_MIPSEL)
```

执行autoconf 生成的diff 如上述，autom4te.cache除外

2022-01-25 15:34 UTC, xen0n commented
我重新看了下，除了生成代码的疑问之外（我还没有自己验证），这里的 `loongarch64-linux-gnu` 也是旧世界写法：Python 此处的三元组大体上是跟随 Debian multiarch tuples 的（从 MIPS 的 ABI 写法可以看出），而 Debian multiarch tuples 按照[规范](https://github.com/loongson/LoongArch-Documentation/blob/a8a004148734445480659a5e25ef985817881341/docs/LoongArch-toolchain-conventions-EN.adoc) Table 12 的规定，大概是要像下面这样改的：

```diff
diff --git a/configure.ac b/configure.ac
index a0fbe41..c4fe61b 100644
--- a/configure.ac
+++ b/configure.ac
@@ -884,6 +884,20 @@ cat >> conftest.c <<EOF
         hppa-linux-gnu
 # elif defined(__ia64__)
         ia64-linux-gnu
+# elif defined(__loongarch__)
+#  if defined(__loongarch64)
+#   if defined(__loongarch_soft_float)
+        loongarch64-linux-gnusf
+#   elif defined(__loongarch_single_float)
+        loongarch64-linux-gnuf32
+#   elif defined(__loongarch_double_float)
+        loongarch64-linux-gnuf64
+#   else
+#    error unknown platform triplet
+#   endif
+#  else
+#   error unknown platform triplet
+#  endif
 # elif defined(__m68k__) && !defined(__mcoldfire__)
         m68k-linux-gnu
 # elif defined(__mips_hard_float) && defined(__mips_isa_rev) && (__mips_isa_rev >=6) && defined(_MIPSEL)
```

你们看下？

2022-01-26 01:40 UTC, loongson-zn commented
新世界的事情一直没怎么关注，以为只是内核和C库结构体的一些变化，这个事情会尽快去确认、处理，多谢提示。 @xen0n

2022-01-26 02:56 UTC, loongson-zn commented
已经找编译器组的同事确认，以后按照新世界的标准提交，我将重新提交

2022-01-26 04:52 UTC, loongson-zn commented
https://github.com/loongarch64/cpython/pull/2#issue-1114625169
上游更新速度较快，更新git仓库后，创建一个新的分支提交

2022-01-26 05:31 UTC, xen0n commented
可，那这个先 close 了哈

2022-01-26 05:31 UTC, closed without merging